module LanguageServer
  module Protocol
    module Interface
      class FullDocumentDiagnosticReport
        def initialize: (kind: untyped, items: untyped) -> void
      end
    end

    module Constant
      module MessageType
        ERROR: Integer
      end
    end
  end
end
