module RuboCop
  type rubyExtractorResult = Array[{ offset: Integer, processed_source: ProcessedSource }]?

  interface _RubyExtractor
    def call: (ProcessedSource) -> rubyExtractorResult
  end

  class Config
    # Extend gem_rbs_collection's definition to allow optional arguments
    def initialize: () -> void
                  | ...
  end

  module Plugin
    def self.integrate_plugins: (Config config, Array[String] plugins) -> void
  end

  class ConfigStore
    def options_config=: (String? path) -> void
    def for_pwd: () -> Config
  end

  module Cop
    class Severity
      attr_reader name: Symbol
      def level: () -> Integer
    end

    class Offense
      attr_reader cop_name: String
      attr_reader message: String
      attr_reader severity: Severity
      attr_reader line: Integer
      attr_reader column: Integer
      attr_reader location: Parser::Source::Range
    end
  end

  module Lsp
    class StdinRunner
      def self.ruby_extractors: () -> Array[_RubyExtractor]

      def initialize: (ConfigStore config_store) -> void
      def run: (String path, String source, Hash[untyped, untyped] options) -> void
      def offenses: () -> Array[Cop::Offense]
      def formatted_source: () -> String
    end
  end

  module AST
    class ProcessedSource
      attr_reader ruby_version: Float
      attr_reader path: String?
      attr_reader parser_engine: Symbol?

      # A fix for https://github.com/rubocop/rubocop-ast/blob/master/lib/rubocop/ast/processed_source.rb
      def initialize: (String source, Float ruby_version, ?String? path, ?parser_engine: Symbol?, ?prism_result: Prism::ParseResult) -> void
                    | ...

      include Ext::ProcessedSource
    end
  end

  class CommentConfig
  end

  module Ext
    module ProcessedSource
      attr_accessor registry: untyped
      attr_accessor config: untyped

      def comment_config: () -> CommentConfig
      def disabled_line_ranges: () -> untyped
    end
  end

  class Runner
    def self.ruby_extractors: () -> Array[_RubyExtractor]
  end
end
