module RuboCop
  module Lsp
    class StdinRunner < Runner
      def initialize: (ConfigStore config_store) -> void
      def run: (String path, String source, Hash[untyped, untyped] options) -> void
      def offenses: () -> Array[Cop::Offense]
    end
  end

end
