module RubyLsp
  module Interface = LanguageServer::Protocol::Interface
  module Constant = LanguageServer::Protocol::Constant

  class Addon
  end

  class BaseServer
    def send_message: (untyped message) -> void
    def send_empty_response: (Integer id) -> void
  end

  class GlobalState
    attr_reader workspace_path: String
  end

  class Server < BaseServer
    def text_document_diagnostic: (Hash[untyped, untyped]) -> void
  end

  class Store
    @global_state: GlobalState
    @state: Hash[String, Document[untyped]]

    def set: (uri: URI::Generic, source: String, version: Integer, language_id: Symbol) -> Document[untyped]
  end
end
