#!/bin/bash
# .claude/hooks/protect-sig-files.sh
#
# Prevents direct editing of auto-generated RBS type definition files.
# Type definitions in */sig/ directories are managed by PostToolUse hooks.

TOOL_NAME="$CLAUDE_TOOL_NAME"
FILE_PATH="$CLAUDE_TOOL_PARAM_file_path"
COMMAND="$CLAUDE_TOOL_PARAM_command"

# Block Write/Edit operations on sig/ files
if [[ "$TOOL_NAME" == "Write" || "$TOOL_NAME" == "Edit" ]]; then
    if [[ "$FILE_PATH" == */sig/* ]]; then
        echo "❌ ERROR: Direct editing of sig/ files is not allowed."
        echo "📝 Type definitions are auto-generated by PostToolUse hook."
        echo "💡 Modify inline RBS annotations in .rb files instead."
        exit 1
    fi
fi

# Block manual rbs-inline execution
if [[ "$TOOL_NAME" == "Bash" ]]; then
    if [[ "$COMMAND" =~ rbs-inline ]]; then
        echo "❌ ERROR: Manual rbs-inline execution is not allowed."
        echo "🔄 Type definitions are auto-generated by hooks."
        exit 1
    fi
fi

exit 0
