AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
