AllCops:
  TargetRubyVersion: 3.1

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
